// AUTO-GENERATED by scripts/record-samples.ts — do not edit by hand.
// The live model's deterministic (temperature 0) read of each public/samples/
// photo, so MOCK mode returns EXACTLY what LIVE mode does. Regenerate with
// 'npm run samples:record' after changing the sample photos.
import type { Extraction } from '../extraction/schema';

export const SAMPLE_READS: Record<string, Extraction> = {
  "bourbon-widow-jane.jpeg": {
    "brand_name": "Widow Jane",
    "class_type": "Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": null,
      "proof": null
    },
    "net_contents": null,
    "producer_bottler": "Widow Jane Distillery, Brooklyn, NY",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "doctored-bourbon-38pct.png": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 38,
      "proof": 76
    },
    "net_contents": "750 mL",
    "producer_bottler": "Stone's Throw Distillery, Louisville, KY",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "malt-hefeweizen.png": {
    "brand_name": "Hefeweizen",
    "class_type": "Imported Beer",
    "alcohol_content": {
      "abv_percent": null,
      "proof": null
    },
    "net_contents": "500 ML",
    "producer_bottler": "Malt & Hop Brewery, Hyattsville, Maryland",
    "country_of_origin": "Germany",
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": false,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "organic.png": {
    "brand_name": "CHAMISAL VINEYARDS",
    "class_type": "Chardonnay",
    "alcohol_content": {
      "abv_percent": null,
      "proof": null
    },
    "net_contents": "750ML",
    "producer_bottler": "Chamisal Vineyards, San Luis Obispo, CA",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) ACCORDING TO THE SURGEON GENERAL, WOMEN SHOULD NOT DRINK ALCOHOLIC BEVERAGES DURING PREGNANCY BECAUSE OF THE RISK OF BIRTH DEFECTS. (2) CONSUMPTION OF ALCOHOLIC BEVERAGES IMPAIRS YOUR ABILITY TO DRIVE A CAR OR OPERATE MACHINERY, AND MAY CAUSE HEALTH PROBLEMS.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": null,
      "remainder_bold": null,
      "is_continuous": false
    }
  },
  "spirit-ouzo.png": {
    "brand_name": "12 OUZO",
    "class_type": null,
    "alcohol_content": {
      "abv_percent": null,
      "proof": null
    },
    "net_contents": null,
    "producer_bottler": "DISTILLED AND BOTTLED IN GREECE BY KARATHIMME - BROTHERS S.A. RILEY",
    "country_of_origin": "GREECE",
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) ACCORDING TO THE SURGEON GENERAL, WOMEN SHOULD NOT DRINK ALCOHOLIC BEVERAGES DURING PREGNANCY BECAUSE OF THE RISK OF BIRTH DEFECTS. (2) CONSUMPTION OF ALCOHOLIC BEVERAGES IMPAIRS YOUR ABILITY TO DRIVE A CAR OR OPERATE MACHINERY, AND MAY CAUSE HEALTH PROBLEMS.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": null,
      "remainder_bold": null,
      "is_continuous": true
    }
  },
  "spirit-tequila.png": {
    "brand_name": null,
    "class_type": null,
    "alcohol_content": {
      "abv_percent": 40,
      "proof": 80
    },
    "net_contents": null,
    "producer_bottler": "SIETE BUCKS SPIRITS, WHITE PLAINS, NY",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) ACCORDING TO THE SURGEON GENERAL, WOMEN SHOULD NOT DRINK ALCOHOLIC BEVERAGES DURING PREGNANCY BECAUSE OF THE RISK OF BIRTH DEFECTS. (2) CONSUMPTION OF ALCOHOLIC BEVERAGES IMPAIRS YOUR ABILITY TO DRIVE A CAR OR OPERATE MACHINERY, AND MAY CAUSE HEALTH PROBLEMS.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "whiskey.png": {
    "brand_name": "REDBREAST",
    "class_type": "Pot Still Whiskey",
    "alcohol_content": {
      "abv_percent": null,
      "proof": null
    },
    "net_contents": "750 mL",
    "producer_bottler": "Pernod Ricard USA, New York, NY",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) ACCORDING TO THE SURGEON GENERAL, WOMEN SHOULD NOT DRINK ALCOHOLIC BEVERAGES DURING PREGNANCY BECAUSE OF THE RISK OF BIRTH DEFECTS. (2) CONSUMPTION OF ALCOHOLIC BEVERAGES IMPAIRS YOUR ABILITY TO DRIVE A CAR OR OPERATE MACHINERY, AND MAY CAUSE HEALTH PROBLEMS.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": true,
      "is_continuous": true
    }
  },
  "wine-1.png": {
    "brand_name": "Hawk's Shadow",
    "class_type": "Orange Muscat",
    "alcohol_content": {
      "abv_percent": 13.68,
      "proof": null
    },
    "net_contents": null,
    "producer_bottler": "Hawk's Shadow Estate, Dripping Springs, Texas",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "ACCORDING TO THE SURGEON GENERAL, WOMEN SHOULD NOT DRINK ALCOHOLIC BEVERAGES DURING PREGNANCY BECAUSE OF THE RISK OF BIRTH DEFECTS. CONSUMPTION OF ALCOHOLIC BEVERAGES IMPAIRS YOUR ABILITY TO DRIVE A CAR OR OPERATE MACHINERY, AND MAY CAUSE HEALTH PROBLEMS.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": false
    }
  },
  "wine-2.jpg": {
    "brand_name": null,
    "class_type": null,
    "alcohol_content": {
      "abv_percent": null,
      "proof": null
    },
    "net_contents": null,
    "producer_bottler": "William Grant and Sons, Inc., New York, NY",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) ACCORDING TO THE SURGEON GENERAL, WOMEN SHOULD NOT DRINK ALCOHOLIC BEVERAGES DURING PREGNANCY BECAUSE OF THE RISK OF BIRTH DEFECTS. (2) CONSUMPTION OF ALCOHOLIC BEVERAGES IMPAIRS YOUR ABILITY TO DRIVE A CAR OR OPERATE MACHINERY, AND MAY CAUSE HEALTH PROBLEMS.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": null,
      "remainder_bold": null,
      "is_continuous": true
    }
  },
  "wine-merlot.png": {
    "brand_name": "ABC WINERY",
    "class_type": "AMERICAN MERLOT",
    "alcohol_content": {
      "abv_percent": 15.5,
      "proof": null
    },
    "net_contents": "750 ML",
    "producer_bottler": "XYZ VINTNERS, CITY, STATE",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) ACCORDING TO THE SURGEON GENERAL, WOMEN SHOULD NOT DRINK ALCOHOLIC BEVERAGES DURING PREGNANCY BECAUSE OF THE RISK OF BIRTH DEFECTS. (2) CONSUMPTION OF ALCOHOLIC BEVERAGES IMPAIRS YOUR ABILITY TO DRIVE A CAR OR OPERATE MACHINERY, AND MAY CAUSE HEALTH PROBLEMS. CONTAINS SULFITES",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "wine-sake.png": {
    "brand_name": "CHICHIBU NISHIKI",
    "class_type": "JUNMAI GINJO SAKE",
    "alcohol_content": {
      "abv_percent": 15.5,
      "proof": null
    },
    "net_contents": "720 ML",
    "producer_bottler": "Yao Honten in Chichibu, Saitama, Japan",
    "country_of_origin": "PRODUCT OF JAPAN",
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) ACCORDING TO THE SURGEON GENERAL, WOMEN SHOULD NOT DRINK ALCOHOLIC BEVERAGES DURING PREGNANCY BECAUSE OF THE RISK OF BIRTH DEFECTS. (2) CONSUMPTION OF ALCOHOLIC BEVERAGES IMPAIRS YOUR ABILITY TO DRIVE A CAR OR OPERATE MACHINERY, AND MAY CAUSE HEALTH PROBLEMS.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  }
};
