// AUTO-GENERATED by scripts/render-fixtures.ts — do not edit by hand.
// Maps a fixture image's SHA-256 to the extraction a perfect vision read yields,
// so mock mode returns the right PASS/FLAG/FAIL for each uploaded fixture.
import type { Extraction } from './schema';

export const FIXTURE_EXTRACTIONS: Record<string, Extraction> = {
  "2375a5f2042420b7396c66da30a6e89e2e4a9a4e12f542368b74eaacbda777a1": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 45,
      "proof": 90
    },
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "ed776d3e1ecbbd25d949b339b897e286f471809e8c6c459ddc7def08296849a7": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 45,
      "proof": 90
    },
    "government_warning": {
      "present": true,
      "text": "Government Warning: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": false,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "2b2af2add1a5c7c4d25e7004f63efd815e0259c024915a5966cb04b5737f9ed1": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 45,
      "proof": 90
    },
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": true,
      "is_continuous": true
    }
  },
  "9ad08cb839ae73672cd9196d7354705ca243151545f27c2b04b12bffc7dc8291": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 45,
      "proof": 90
    },
    "government_warning": {
      "present": false,
      "text": null,
      "first_two_words_all_caps": null,
      "first_two_words_bold": null,
      "remainder_bold": null,
      "is_continuous": null
    }
  },
  "7d19529ec57922cdab6af8276eef6d7234ff6ddc951e04e0c87f218203ee5ad5": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 38,
      "proof": 76
    },
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "3681ffa7afb2fed443d18dacd1b626ac75a965aa125c0573f9b340d33db2d39c": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 45,
      "proof": 100
    },
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  }
};
