// AUTO-GENERATED by scripts/render-fixtures.ts — do not edit by hand.
// Maps a fixture image's SHA-256 to the extraction a perfect vision read yields,
// so mock mode returns the right PASS/FLAG/FAIL for each uploaded fixture.
import type { Extraction } from './schema';

export const FIXTURE_EXTRACTIONS: Record<string, Extraction> = {
  "820bab3536025e50fa532adec1f4775a3b9c93352e8531f102fa69753effa191": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 45,
      "proof": 90
    },
    "net_contents": "750 mL",
    "producer_bottler": "Stone's Throw Distillery, Louisville, KY",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "e9f5c5b9845e4e1242396444f92079c6fdc8d0a9f7e7c2508ed4e4fd07098830": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 45,
      "proof": 90
    },
    "net_contents": "750 mL",
    "producer_bottler": "Stone's Throw Distillery, Louisville, KY",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "Government Warning: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": false,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "a35732dd17845d07b82df6cd3153fe7c259523e6b36f9654663cd510bace1f27": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 45,
      "proof": 90
    },
    "net_contents": "750 mL",
    "producer_bottler": "Stone's Throw Distillery, Louisville, KY",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": true,
      "is_continuous": true
    }
  },
  "d3fcc7f0527770552df9f44639f7cc36ceda56ec678e969b326b267105e97fa3": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 45,
      "proof": 90
    },
    "net_contents": "750 mL",
    "producer_bottler": "Stone's Throw Distillery, Louisville, KY",
    "country_of_origin": null,
    "government_warning": {
      "present": false,
      "text": null,
      "first_two_words_all_caps": null,
      "first_two_words_bold": null,
      "remainder_bold": null,
      "is_continuous": null
    }
  },
  "ff83182393cbf29102465f782b37b9acbc2628e0ed375784233d97575240adc5": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 38,
      "proof": 76
    },
    "net_contents": "750 mL",
    "producer_bottler": "Stone's Throw Distillery, Louisville, KY",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "9cc196f9b2943113c982d52fbecb6a988dad1ba31671d2e9bf7eb20fd318e3ca": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 45,
      "proof": 100
    },
    "net_contents": "750 mL",
    "producer_bottler": "Stone's Throw Distillery, Louisville, KY",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "7c55f7a78ce001b0a64f599fd39d45531437db601fedae95ee68b9ea4aed3b39": {
    "brand_name": "STONE'S THROW",
    "class_type": "Kentucky Straight Bourbon Whiskey",
    "alcohol_content": {
      "abv_percent": 45,
      "proof": 90
    },
    "net_contents": "750 mL",
    "producer_bottler": "Stone's Throw Distillery, Louisville, KY",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy. (2) Consumption of alcoholic beverages may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "a65463531fdaf28905a224b4a0d13156468e256a965e60fa091ab53c151b2f3f": {
    "brand_name": "NORTH STAR",
    "class_type": "Vodka",
    "alcohol_content": {
      "abv_percent": 38,
      "proof": 76
    },
    "net_contents": "750 mL",
    "producer_bottler": "North Star Spirits, Portland, OR",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  },
  "ab03afe0376c9b61c247f5546f0ee4bf339309045215a90e6a714e9254245039": {
    "brand_name": "RIVERBEND",
    "class_type": "Cabernet Sauvignon",
    "alcohol_content": {
      "abv_percent": 13.5,
      "proof": null
    },
    "net_contents": "750 mL",
    "producer_bottler": "Riverbend Cellars, Napa, CA",
    "country_of_origin": null,
    "government_warning": {
      "present": true,
      "text": "GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.",
      "first_two_words_all_caps": true,
      "first_two_words_bold": true,
      "remainder_bold": false,
      "is_continuous": true
    }
  }
};
