import { readFile, readdir, writeFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
import type { Extraction } from '../src/lib/extraction/schema';
import { getSharedExtractionProvider } from '../src/lib/extraction/provider';

const MEDIA: Record<string, 'image/png' | 'image/jpeg'> = { '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg' };

async function main() {
  const dir = join(process.cwd(), 'public', 'samples');
  const names = (await readdir(dir)).filter((n) => MEDIA[extname(n).toLowerCase()]).sort();
  const provider = await getSharedExtractionProvider();
  const reads: Record<string, Extraction> = {};
  for (const name of names) {
    const buf = await readFile(join(dir, name));
    const { data } = await provider.extract({ imageBase64: buf.toString('base64'), mediaType: MEDIA[extname(name).toLowerCase()] });
    if (data) reads[name] = data;
    else process.stderr.write(`WARN: no read for ${name}\n`);
    process.stderr.write(`recorded ${name}\n`);
  }
  const out =
    `// AUTO-GENERATED by scripts/record-samples.ts — do not edit by hand.\n` +
    `// The live model's deterministic (temperature 0) read of each public/samples/\n` +
    `// photo, so MOCK mode returns EXACTLY what LIVE mode does. Regenerate with\n` +
    `// 'npm run samples:record' after changing the sample photos.\n` +
    `import type { Extraction } from '../extraction/schema';\n\n` +
    `export const SAMPLE_READS: Record<string, Extraction> = ${JSON.stringify(reads, null, 2)};\n`;
  await writeFile(join(process.cwd(), 'src/lib/samples/reads.generated.ts'), out);
  process.stderr.write(`\nwrote src/lib/samples/reads.generated.ts (${names.length} reads)\n`);
}
main();
