/**
 * Renders each fixture spec to a label image (images/<id>.png) and writes a
 * generated map (image content-hash → "perfect read" extraction) that makes
 * mock mode fixture-aware. Run: npm run fixtures
 */
import { createHash } from 'node:crypto';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';
import { FIXTURES, deriveExtraction, type LabelSpec } from '../src/lib/fixtures/specs';

const ROOT = join(import.meta.dirname, '..');
const IMAGES_DIR = join(ROOT, 'images');
const W = 760;
const H = 580;

function escapeXml(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]!);
}

/** Greedy word-wrap to a character width. */
function wrap(text: string, maxChars: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let line = '';
  for (const w of words) {
    if (line && (line + ' ' + w).length > maxChars) {
      lines.push(line);
      line = w;
    } else {
      line = line ? line + ' ' + w : w;
    }
  }
  if (line) lines.push(line);
  return lines;
}

function warningSvg(spec: LabelSpec, top: number): string {
  if (!spec.warning) {
    return `<text x="${W / 2}" y="${top + 40}" text-anchor="middle" font-family="Arial" font-size="15" fill="#888" font-style="italic">[no government warning printed]</text>`;
  }
  const lines = wrap(spec.warning.text, 64);
  const prefixMatch = spec.warning.text.match(/^(GOVERNMENT WARNING|Government Warning)/);
  const prefix = prefixMatch ? prefixMatch[0] : '';
  const remWeight = spec.warning.remainderBold ? 'bold' : 'normal';
  const preWeight = spec.warning.prefixBold ? 'bold' : 'normal';

  return lines
    .map((ln, i) => {
      const y = top + i * 22;
      if (i === 0 && prefix && ln.startsWith(prefix)) {
        const rest = escapeXml(ln.slice(prefix.length));
        return `<text x="40" y="${y}" font-family="Arial" font-size="15" fill="#111"><tspan font-weight="${preWeight}">${escapeXml(prefix)}</tspan><tspan font-weight="${remWeight}">${rest}</tspan></text>`;
      }
      return `<text x="40" y="${y}" font-family="Arial" font-size="15" font-weight="${remWeight}" fill="#111">${escapeXml(ln)}</text>`;
    })
    .join('\n');
}

function labelSvg(spec: LabelSpec): string {
  const abvLine = [
    spec.abv != null ? `${spec.abv}% Alc./Vol.` : null,
    spec.proof != null ? `${spec.proof} Proof` : null,
  ]
    .filter(Boolean)
    .join('   ·   ');

  // undefined → default; explicit null → not printed on the label.
  const netContents = spec.netContents === undefined ? '750 mL' : spec.netContents;
  const bottler = spec.bottler === undefined ? "Stone's Throw Distillery, Louisville, KY" : spec.bottler;
  const footer = [bottler ? `Bottled by ${bottler}` : null, spec.country ? `Product of ${spec.country}` : null]
    .filter(Boolean)
    .join('   ·   ');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <rect width="${W}" height="${H}" fill="#fdfcf8"/>
  <rect x="14" y="14" width="${W - 28}" height="${H - 28}" fill="none" stroke="#c9a24a" stroke-width="3"/>
  <rect x="22" y="22" width="${W - 44}" height="${H - 44}" fill="none" stroke="#c9a24a" stroke-width="1"/>
  <text x="${W / 2}" y="105" text-anchor="middle" font-family="Georgia, 'Times New Roman', serif" font-size="46" font-weight="bold" fill="#2b2b2b">${escapeXml(spec.brand)}</text>
  <text x="${W / 2}" y="158" text-anchor="middle" font-family="Georgia, serif" font-size="22" fill="#3a3a3a">${escapeXml(spec.classType)}</text>
  <line x1="180" y1="190" x2="${W - 180}" y2="190" stroke="#c9a24a" stroke-width="1"/>
  <text x="${W / 2}" y="232" text-anchor="middle" font-family="Georgia, serif" font-size="22" fill="#2b2b2b">${escapeXml(abvLine || '—')}</text>
  ${netContents ? `<text x="${W / 2}" y="266" text-anchor="middle" font-family="Georgia, serif" font-size="18" fill="#3a3a3a">${escapeXml(netContents)}</text>` : ''}
  <line x1="40" y1="320" x2="${W - 40}" y2="320" stroke="#ddd" stroke-width="1"/>
  ${warningSvg(spec, 360)}
  ${footer ? `<text x="${W / 2}" y="558" text-anchor="middle" font-family="Arial" font-size="12" fill="#666">${escapeXml(footer)}</text>` : ''}
</svg>`;
}

async function main() {
  mkdirSync(IMAGES_DIR, { recursive: true });
  const map: Record<string, unknown> = {};
  const catalog: string[] = [
    '# Fixture label images',
    '',
    'Synthetic distilled-spirits labels, one per compliance scenario. Generated by',
    '`npm run fixtures` from [`src/lib/fixtures/specs.ts`](../src/lib/fixtures/specs.ts).',
    'Each ships with its expected verdict — this is both the demo set and the',
    'measurement corpus. Upload any of these in the app (mock mode needs no key).',
    '',
    '| # | Image | Targets | Expected |',
    '|---|---|---|---|',
  ];

  for (const spec of FIXTURES) {
    const png = await sharp(Buffer.from(labelSvg(spec))).png().toBuffer();
    const file = `${spec.id}.png`;
    writeFileSync(join(IMAGES_DIR, file), png);
    const hash = createHash('sha256').update(png).digest('hex');
    map[hash] = deriveExtraction(spec);
    catalog.push(`| ${spec.id} | \`${file}\` | ${spec.targets} | **${spec.expectedOverall}** — ${spec.expectedNote} |`);
    console.log(`rendered ${file}  (${png.length} bytes, sha ${hash.slice(0, 12)}…)  → ${spec.expectedOverall}`);
  }

  const generated =
    `// AUTO-GENERATED by scripts/render-fixtures.ts — do not edit by hand.\n` +
    `// Maps a fixture image's SHA-256 to the extraction a perfect vision read yields,\n` +
    `// so mock mode returns the right PASS/FLAG/FAIL for each uploaded fixture.\n` +
    `import type { Extraction } from './schema';\n\n` +
    `export const FIXTURE_EXTRACTIONS: Record<string, Extraction> = ${JSON.stringify(map, null, 2)};\n`;
  writeFileSync(join(ROOT, 'src/lib/extraction/fixtures.generated.ts'), generated);
  writeFileSync(join(IMAGES_DIR, 'README.md'), catalog.join('\n') + '\n');
  console.log(`\nWrote ${FIXTURES.length} images, images/README.md, and src/lib/extraction/fixtures.generated.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
